apiVersion: v1
kind: Service
metadata:
  name: lms-frontend
  namespace: lms-app
spec:
  selector:
    app: lms-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
