apiVersion: v1
kind: Service
metadata:
  name: lms-backend
  namespace: lms-app
spec:
  type: NodePort
  selector:
    app: lms-backend
  ports:
    - port: 8078
      targetPort: 8078
      nodePort: 30078  # accessible on your host
